node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
      maven {
            goals('clean')
            goals('package')
            rootPOM("sb-jenkins/pom.xml")
            properties(skipTests: true)
            mavenInstallation('M3')
        }
   }

}
