node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     maven(mavenInstallationName: 'M3') {
       sh 'cd sb-jenkins && mvn clean package -DskipTests ' 
     }
   }
//    stage('docker build/push') {
//      docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
//        def app = docker.build("aschay/docker-sb:${commit_id}", '.').push()
//      }
//    }
}
